Config = {
    ['Weapons'] = {
        ['pistol'] = 'weapon_pistol',
        ['ceramic'] = 'weapon_ceramicpistol',
        ['combat'] = 'weapon_combatpistol',
        ['sns'] = 'weapon_snspistol',
        ['pump'] = 'weapon_pumpshotgun',
        ['marksman'] = 'weapon_marksmanrifle'
    },
    ['WeaponLabels'] = {
        ['pistol'] = 'Standard Pistol',
        ['ceramic'] = 'Ceramic Pistol',
        ['combat'] = 'Combat Pistol',
        ['sns'] = 'SNS Pistol',
        ['pump'] = 'Pump Shotgun',
        ['marksman'] = 'Marksman Rifle'
    },
    ['WeaponModels'] = {
        ['weapon_pistol'] = 'w_pi_pistol',
        ['weapon_ceramicpistol'] = 'w_pi_ceramic_pistol',
        ['weapon_combatpistol'] = 'w_pi_combatpistol',
        ['weapon_snspistol'] = 'w_pi_sns_pistol',
        ['weapon_pumpshotgun'] = 'w_sg_pumpshotgun',
        ['weapon_marksmanrifle'] = 'w_sr_marksmanrifle',
    },
    ['Shops'] = {
        ['ammuone'] = {
            ['menu'] = {
                ['loc'] = vector3(17.81, -1108.72, 29.8),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu1_menu',
                ['heading'] = 70.0,
                ['debugPoly'] = true,
                ['minZ'] = 25.4,
                ['maxZ'] = 30.0,
            },
            ['supplies'] = {
                ['loc'] = vector3(9.75, -1101.27, 29.8),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu1_supply',
                ['heading'] = 340,
                ['debugPoly'] = true,
                ['minZ'] = 25.4,
                ['maxZ'] = 29.4,
            },
            ['craft'] = {
                ['loc'] = vector3(19.98, -1107.5, 29.8),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu1_craft',
                ['heading'] = 340,
                ['debugPoly'] = true,
                ['minZ'] = 26.0,
                ['maxZ'] = 30.0,
            },
            ['showcase'] = vector4(16.64, -1108.25, 29.91, 120.02)
        },
        -- ['ammutwo'] = {
        --     ['menu'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['supplies'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['craft'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     }
        -- },
        ['ammuthree'] = {
            ['menu'] = {
                ['loc'] = vector3(-327.02, 6080.95, 31.45),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu3_menu',
                ['heading'] = 315,
                ['debugPoly'] = true,
                ['minZ'] = 27.65,
                ['maxZ'] = 31.65,
            },
            ['supplies'] = {
                ['loc'] = vector3(-327.66, 6085.67, 31.45),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu3_supply',
                ['heading'] = 315,
                ['debugPoly'] = true,
                ['minZ'] = 28.65,
                ['maxZ'] = 32.65,
            },
            ['craft'] = {
                ['loc'] = vector3(-324.95, 6080.98, 31.45),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu3_craft',
                ['heading'] = 315,
                ['debugPoly'] = true,
                ['minZ'] = 27.65,
                ['maxZ'] = 31.65,
            },
            ['showcase'] = vector4(-328.19, 6082.08, 31.6, 128.98)
        },
        -- ['ammufour'] = {
        --     ['menu'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['supplies'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['craft'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        -- },
        ['ammufive'] = {
            ['menu'] = {
                ['loc'] = vector3(1697.03, 3757.19, 34.71),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu5_menu',
                ['heading'] = 320,
                ['debugPoly'] = true,
                ['minZ'] = 30.91,
                ['maxZ'] = 34.91,
            },
            ['supplies'] = {
                ['loc'] = vector3(1696.2, 3761.86, 34.71),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu5_supply',
                ['heading'] = 320,
                ['debugPoly'] = true,
                ['minZ'] = 31.91,
                ['maxZ'] = 34.91,
            },
            ['craft'] = {
                ['loc'] = vector3(1699.08, 3757.22, 34.71),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu5_craft',
                ['heading'] = 320,
                ['debugPoly'] = true,
                ['minZ'] = 31.11,
                ['maxZ'] = 35.11,
            },
            ['showcase'] = vector4(1695.81, 3758.4, 34.84, 38.7)
        },
        ['ammusix'] = {
            ['menu'] = {
                ['loc'] = vector3(-1311.9, -394.66, 36.7),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu6_menu',
                ['heading'] = 345,
                ['debugPoly'] = true,
                ['minZ'] = 33.10,
                ['maxZ'] = 37.10,
            },
            ['supplies'] = {
                ['loc'] = vector3(-1307.05, -397.29, 36.7),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu6_supply',
                ['heading'] = 345,
                ['debugPoly'] = true,
                ['minZ'] = 33.90,
                ['maxZ'] = 37.90,
            },
            ['craft'] = {
                ['loc'] = vector3(-1310.09, -393.61, 36.7),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu6_craft',
                ['heading'] = 345,
                ['debugPoly'] = true,
                ['minZ'] = 32.90,
                ['maxZ'] = 36.90,
            },
            ['showcase'] = vector4(-1308.42, -394.07, 36.83, 256.58)
        },
        ['ammuseven'] = {
            ['menu'] = {
                ['loc'] = vector3(-1113.31, 2696.95, 18.74),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu7_menu',
                ['heading'] = 312,
                ['debugPoly'] = true,
                ['minZ'] = 14.74,
                ['maxZ'] = 18.74,
            },
            ['supplies'] = {
                ['loc'] = vector3(-1113.98, 2702.0, 18.55),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu7_supply',
                ['heading'] = 310,
                ['debugPoly'] = true,
                ['minZ'] = 15.75,
                ['maxZ'] = 19.75,
            },
            ['craft'] = {
                ['loc'] = vector3(-1111.35, 2696.83, 18.7),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu7_craft',
                ['heading'] = 310,
                ['debugPoly'] = true,
                ['minZ'] = 14.90,
                ['maxZ'] = 18.90,
            },
            ['showcase'] = vector4(-1114.43, 2698.28, 18.69, 45.9)
        },
        -- ['ammueight'] = {
        --     ['menu'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['supplies'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     },
        --     ['craft'] = {
        --         ['loc'] = ,
        --         ['length'] = ,
        --         ['width'] = ,
        --         ['name'] = ,
        --         ['heading'] = ,
        --         ['debugPoly'] = ,
        --         ['minZ'] = ,
        --         ['maxZ'] = ,
        --     }
        -- },
        ['ammunine'] = {
            ['menu'] = {
                ['loc'] = vector3(813.66, -2154.37, 29.62),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu9_menu',
                ['heading'] = 1.0,
                ['debugPoly'] = true,
                ['minZ'] = 25.82,
                ['maxZ'] = 29.82,
            },
            ['supplies'] = {
                ['loc'] = vector3(823.76, -2158.6, 29.62),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu9_supply',
                ['heading'] = 0,
                ['debugPoly'] = true,
                ['minZ'] = 25.22,
                ['maxZ'] = 29.22,
            },
            ['craft'] = {
                ['loc'] = vector3(812.05, -2156.15, 29.62),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu9_craft',
                ['heading'] = 0,
                ['debugPoly'] = true,
                ['minZ'] = 25.82,
                ['maxZ'] = 29.82,
            },
            ['showcase'] = vector4(814.69, -2154.41, 29.73, 268.98)
        },
        ['ammuten'] = {
            ['menu'] = {
                ['loc'] = vector3(-659.97, -939.44, 21.83),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu10_menu',
                ['heading'] = 0,
                ['debugPoly'] = true,
                ['minZ'] = 18.03,
                ['maxZ'] = 22.03,
            },
            ['supplies'] = {
                ['loc'] = vector3(-657.06, -935.26, 21.83),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu10_supply',
                ['heading'] = 0,
                ['debugPoly'] = true,
                ['minZ'] = 19.03,
                ['maxZ'] = 23.03,
            },
            ['craft'] = {
                ['loc'] = vector3(-658.44, -940.8, 21.83),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu10_craft',
                ['heading'] = 0,
                ['debugPoly'] = true,
                ['minZ'] = 18.23,
                ['maxZ'] = 22.23,
            },
            ['showcase'] = vector4(-659.9, -937.66, 21.97, 2.29)
        },
        ['ammuelev'] = {
            ['menu'] = {
                ['loc'] = vector3(247.54, -50.73, 69.94),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu11_menu',
                ['heading'] = 340,
                ['debugPoly'] = true,
                ['minZ'] = 66.14,
                ['maxZ'] = 70.14,
            },
            ['supplies'] = {
                ['loc'] = vector3(250.5, -54.9, 69.94),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu11_supply',
                ['heading'] = 340,
                ['debugPoly'] = true,
                ['minZ'] = 66.14,
                ['maxZ'] = 71.14,
            },
            ['craft'] = {
                ['loc'] = vector3(245.7, -51.69, 69.94),
                ['length'] = 1.0,
                ['width'] = 1.0,
                ['name'] = 'ammu11_craft',
                ['heading'] = 340,
                ['debugPoly'] = true,
                ['minZ'] = 66.34,
                ['maxZ'] = 70.34,
            },
            ['showcase'] = vector4(249.1, -51.34, 70.08, 146.79)
        },
    }
}